

services: 
  chatbot-service:
    build: 
      context: ./chatbot-service
      dockerfile: Dockerfile
    container_name: chatbot_service
    ports:
      - "8001:8000"
    env_file:
      - ./chatbot-service/.env
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
