services: 
  redis:
    image: redis:6
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - backend_network
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    environment:
      - REDIS_HOSTS=local:redis_service:6379
    ports:
      - "8081:8081"
    networks:
      - backend_network
    depends_on:
      - redis
    restart: always

  chatbot-service:
    build: 
      context: ./chatbot-service
      dockerfile: Dockerfile
    container_name: chatbot_service
    ports:
      - "8001:8000"
    env_file:
      - ./chatbot-service/.env
    environment:
      - REDIS_HOST=redis_service
    depends_on:
      - redis
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
