services: 
  redis:
    image: redis:6
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - backend_network
    restart: always

  parking-management-service:
    build: 
      context: ./parking-management-service
      dockerfile: Dockerfile
    container_name: parking_management_service
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis_service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - redis
      - discovery-server
    networks:
      - backend_network
    restart: always

  navigation-service:
    build: 
      context: ./navigation-service
      dockerfile: Dockerfile
    container_name: navigation_service
    ports:
      - "8003:8003"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
    networks:
      - backend_network
    restart: always

  discovery-server:
    build: 
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery_server
    ports:
      - "8761:8761"
    networks:
      - backend_network
    restart: always

  api-gateway-service:
    build: 
      context: ./api-gateway-service
      dockerfile: Dockerfile
    container_name: api_gateway_service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - navigation-service
      - parking-management-service
    networks:
      - backend_network
    restart: always

networks:
  backend_network:
    driver: bridge 