services: 
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"   # RabbitMQ mesajlaşma portu
      - "15672:15672" # Yönetim arayüzü portu
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest  
    networks:
      - backend_network
    restart: always

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8050:8050"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

      - PARKING_MANAGEMENT_SERVICE_URL=http://parking-management-service:8081
    depends_on:
      - rabbit-mq
    restart: always
    networks:
      - backend_network

  parking-management-service:
    build: 
      context: ./parking-management-service
      dockerfile: Dockerfile
    container_name: parking_management_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      # Neon DB bağlantısı application.properties'de tanımlı olduğu için burada ek ayara gerek yok
      - SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES=true
    depends_on:
      - rabbit-mq
    restart: always
    networks:
      - backend_network

  notification-service:
    build: 
      context: ./notification-service
      dockerfile: dockerfile
    container_name: notification_service
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - USER_SERVICE_URL=http://user-service:8050
    depends_on:
      - rabbit-mq
      - user-service
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge